server:
  port: 8084

spring:
  application:
    name: gain-experience-attachments
  datasource:
    url: jdbc:mysql://localhost:3306/how2java?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
    timeout: 100ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml

feign:
  hystrix:
    enabled: true
security:
  oauth2:
    client:
      client-id: client_id
      client-secret: 123456
      user-authorization-uri: http://GAIN-EXPERIENCE-AUTHORITY-SECURITY/oauth/authorize
      access-token-uri: http://GAIN-EXPERIENCE-AUTHORITY-SECURITY/oauth/token
#    resource:
#      id: client_id
#      user-info-uri: user-info
    authorization:
      check-token-access: http://GAIN-EXPERIENCE-AUTHORITY-SECURITY/oauth/check_token
