server:
  port: 8082
spring:
  application:
    name: gain-experience-authority-security
  redis:
    host:
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

