server:
  port: 8082

spring:
  application:
    name: gain-experience-authority-security
  datasource:
    url: jdbc:mysql://localhost:3306/gain_experience_authority?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
  security:
    user:
      name: anumbrella
      password: 123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      enabled: true
